BCON-334: pagination support in proof
icanbwell/fhirproof pull request #6
Opened 2021-06-28 01:06 UTC by jmhungdev

2021-07-06 13:15 UTC, dominathan requested changes
I didn't pull it down yet but make these changes and I will.

Also, this doesn't do any sort of pagination for the `.find` method base.model.  We will need to copy this ticket for history methods if that is what you're going to do.  Second, most of these changes look like they are for history storage, so make sure to reference that in the commit and the branch name too, .e.g

BCON-334-BCON-387

2021-07-06 13:15 UTC, dominathan commented on src/base-fhir.model.js
> +      let historyDeleted = Object.assign({}, historyDoc, { response: { status: '200' } });
Status code should be 204, status codes should follow what we are returning to the user.  See https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

If we're returning data to the user, is should be 200.  I don't think we do but double check.

2021-07-06 13:15 UTC, dominathan commented on src/base-fhir.model.js
> +        let historyNotFoundError = Object.assign({}, historyDoc, { response: { status: '400' } });
If it's not found, 404

2021-07-06 13:15 UTC, dominathan commented on src/base-fhir.model.js
> +      let historyError = Object.assign({}, historyDoc, { response: { status: '400' } });
400 generally implies the user made a badrequest.  I'd say if this happens. we did something wrong, so it's 500

2021-07-06 13:15 UTC, dominathan commented on src/base-fhir.model.js
> +    this.BaseURL = this.baseUrl || 'http://no-baseurl-specified';
fhir spec'd uris need to have protocol and extensions.

2021-07-06 13:15 UTC, dominathan commented on src/base-fhir.model.js
> +    this.BaseURL = this.baseUrl || 'http://no-baseurl-specified';
we only capitalized Resource because it was a javascript constructor, so it's supposed to be capitalized. baseUrl is not.

2021-07-06 13:15 UTC, dominathan commented on src/base-fhir.model.js
> +  constructor(collectionName, resourceName, baseUrl) {
add a :param: comment above in the jsdoc telling people what baseUrl is doing.  Otherwise it's hard to know if you are a developer looking at the code.

2021-07-06 13:15 UTC, dominathan commented on src/base-fhir.model.js
> +  static async history(id, pageNumber = 1, nPerPage = 1, options = {}) {
I need to see some tests to see how pagination is working here.

2021-07-07 18:02 UTC, jmhungdev commented
Added a test for `.history()`

2021-07-09 11:15 UTC, dominathan requested changes

2021-07-09 11:15 UTC, dominathan commented on src/base-fhir.model.js
> + * @param {string} baseUrl - the base url of the server
`the base url of the server used for populating history docs in the history collection

2021-07-09 11:15 UTC, dominathan commented on src/base-fhir.model.js
> +  constructor(collectionName, resourceName, baseUrl) {
Need a default param here because you have the equivalent in the initalize method.   So if someone calls 
new Organization() , baseUrl will be undefined.
```
//somewhere near the top
DEFAULT_BASE_URL = 'http://no-baseurl-specificed'

// then in constrcutor
constructor(collectionName, resourceName, baseUrl = DEFAULT_BASE_URL)

// and replace line 34 with the DEFAULT_BASE_URL instead of hard coded string.

2021-07-09 14:37 UTC, dominathan requested changes

2021-07-09 14:37 UTC, dominathan commented on src/base-fhir.model.js
> +  constructor(collectionName, resourceName, baseUrl) {
I don't see these changes.

2021-07-09 14:51 UTC, dominathan approved these changes

2021-07-09 15:06 UTC, merged